# build code

commit_id: fc005bd05330b2d987479d7e1dcc510a9c639551
branch_name: main
code_repo: https://github.com/alibaba/DeepRec.git
build_image_repo: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-build:ubuntu18.04-py38-220627
base_image_modelzoo: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:base-py38
base_image_deepRec: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec:base-py38
image_TAG: 220708-077f3e1

#test model:
test_model: 
        - DLRM
          # - WDL
          #- DeepFM
          #- DSSM
          #- DIEN
          #- DIN
          #- ESMM
          #- DBMTL
          #- MMoE
          #- SimpleMultiTask
          # - BST

#test images
deeprec_test_image: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:220707-9a747e4
tf_test_image: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf

#batchsize map<model,batchsize>
model_batchsize:
  WDL: 512
  DLRM: 512
  DeepFM: 512
  DSSM: 4096
  DIEN: 512
  DIN: 512
  ESMM: 512
  DBMTL: 512
  MMoE: 512
  SimpleMultiTask: 512
  BST: 512

#args for deeprec
#like --emb_fusion true
modelArgs:

#tf on/off
stocktf: on

# set cpu
cpu_sets: 24-47

#set gpu
gpu_sets: 

# env config 
env_var:
  - export START_STATISTIC_STEP=100
  - export STOP_STATISTIC_STEP=110

