whl_address: https://deeprec-whl.oss-cn-beijing.aliyuncs.com/tensorflow-1.15.5%2Bdeeprec2201-220408%2B701d5fd-cp36-cp36m-linux_x86_64.whl
deeprec_base_img: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec:tf
modelzoo_base_img: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf